### PR TITLE
Add Scraper for ComicK

### PR DESCRIPTION
**Pull request by balajsra**
Followed the API Reference to query comick.fun for mangas, associated chapters, and page images.

### CODE REVIEW

**Comment by balajsra** [comment]
Amended my original commit to add a link to the scraper in the README and re-ordered the scrapers in the README to be in alphabetical order.

**Comment by balajsra** [comment]
It probably isn't totally working yet, I only tested it on Omniscient Reader's Viewpoint so far.

**Comment by balajsra** [comment]
Found and fixed an error when testing Kaguya-sama.

**Comment by metafates** [comment]
Thank you for amazing work! It's nice to have an example of using API rather than HTML parsing

**Pull request merged**
